[package]
name = "imgur-enumerator"
version = "0.1.0"
authors = ["lle-bout"]
edition = "2018"

[dependencies]
rand = "0.7"
hyper = "0.12"
futures = "0.1"
tokio = "0.2"
serenity = "0.5"
hyper-tls = "0.3"
clap = "2"
